//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacao
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Data { get; set; }
        public string Description { get; set; }
        public long FitId { get; set; }
        public string Identificador { get; set; }
    }
}
